require("dotenv").config({ path: ".env" })
import { TopicNew, insertTopics } from "../lib/db/topic"
import { SourceNew, insertSources } from "../lib/db/source"
import { db } from "../lib/db"

const SOURCES: Array<SourceNew> = [
  {
    title: "Judgment & Decision Making",
    type: "Journal",
    url_home:
      "https://www.cambridge.org/core/journals/judgment-and-decision-making/information/about-this-journal",
    url_rss:
      "https://www.cambridge.org/core/rss/product/id/FDD872CC2D357744AF3372313641EB91",
    update_frequency: "Ad hoc",
    last_checked: "2023-06-12",
    geo_region: "USA",
    open_access: true,
    notes: "Daily alert added in Cambridge UP account",
  },
  {
    title: "Social Psychology and Personality Science",
    type: "Journal",
    url_home: "https://journals.sagepub.com/home/spp",
    url_rss:
      "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=sppa&type=etoc&feed=rss",
    update_frequency: "Ad hoc",
    last_checked: "2023-06-15",
    geo_region: null,
    open_access: true,
    notes: "@SagePsychology - umbrella twitter",
  },
  {
    title: "Psychological Science (APS)",
    type: "Journal",
    url_home: "https://journals.sagepub.com/home/PSS",
    url_rss:
      "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=pssa&type=etoc&feed=rss",
    update_frequency: "Ad hoc",
    last_checked: "2023-06-15",
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "Journal of Articles in support of the Null Hypothesis",
    type: "Journal",
    url_home: "https://www.jasnh.com/",
    url_rss: "https://www.jasnh.com/jasnhrss.xml",
    update_frequency: "Twice a year",
    last_checked: "2023-06-15",
    geo_region: "USA",
    open_access: true,
    notes: "No email alert option",
  },
  {
    title: "Behavioural Public Policy",
    type: "Journal",
    url_home:
      "https://www.cambridge.org/core/journals/behavioural-public-policy",
    url_rss:
      "https://www.cambridge.org/core/rss/product/id/E1EF0B344C8E8750A474259A311582EF",
    update_frequency: "Every few days",
    last_checked: "2023-07-14",
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "Quarterly Journal of Economics",
    type: "Journal",
    url_home: "https://academic.oup.com/qje/issue/138/3",
    url_rss: "https://academic.oup.com/rss/site_5504/OpenAccess.xml",
    update_frequency: "Quarterly",
    last_checked: "2023-08-03",
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "American Economic Review",
    type: "Journal",
    url_home: "aeaweb.org/journals/aer",
    url_rss: "https://www.aeaweb.org/research/rss-feed",
    update_frequency: "Monthly",
    last_checked: null,
    geo_region: null,
    open_access: false,
    notes: null,
  },
  {
    title: "APA Psychological Bulletin",
    type: "Journal",
    url_home: "https://www.apa.org/pubs/journals/bul",
    url_rss: "https://psycnet.apa.org/journals/bul.rss",
    update_frequency: "Monthly",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "Nature: Human Behaviour",
    type: "Journal",
    url_home: "https://www.nature.com/nathumbehav/",
    url_rss: "https://www.nature.com/nathumbehav.rss",
    update_frequency: "Every few days",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "Cognition",
    type: "Journal",
    url_home: "https://www.sciencedirect.com/journal/cognition/vol/240/suppl/C",
    url_rss: "https://rss.sciencedirect.com/publication/science/00100277",
    update_frequency: "Monthly",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: "Can't find on feedly",
  },
  {
    title: "Journal of Behavioural Decision Making",
    type: "Journal",
    url_home: "https://onlinelibrary.wiley.com/journal/10990771",
    url_rss: "https://onlinelibrary.wiley.com/feed/10990771/most-recent",
    update_frequency: "Every few days",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: "Can't find on feedly",
  },
  {
    title: "Journal of Behavioral and Experimental Economics",
    type: "Journal",
    url_home:
      "https://www.sciencedirect.com/journal/journal-of-behavioral-and-experimental-economics",
    url_rss: "https://rss.sciencedirect.com/publication/science/22148043",
    update_frequency: "Every other month",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: "Not on twitter",
  },
  {
    title: "Journal of Behavioral Public Administration",
    type: "Journal",
    url_home: "https://journal-bpa.org/index.php/jbpa/index",
    url_rss:
      "https://journal-bpa.org/index.php/jbpa/gateway/plugin/WebFeedGatewayPlugin/rss2",
    open_access: true,
  },
  {
    title: "Journal of Behavioral Science & Policy",
    type: "Journal",
    url_home: "https://journals.sagepub.com/toc/BSX/current",
    url_rss:
      "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=bsxa&type=etoc&feed=rss",
    open_access: true,
  },
  {
    title: "Journal of Behavioral and Experimental Finance",
    type: "Journal",
    url_home:
      "https://www.sciencedirect.com/journal/journal-of-behavioral-and-experimental-finance/vol/39/suppl/C",
    url_rss: "https://rss.sciencedirect.com/publication/science/22146350",
    open_access: true,
  },
  {
    title: "Journal of Consumer Psychology",
    type: "Journal",
    url_home: "https://myscp.onlinelibrary.wiley.com/journal/15327663",
    url_rss: "https://myscp.onlinelibrary.wiley.com/feed/15327663/most-recent",
    open_access: true,
  },
  {
    title: "Journal of Economic Psychology",
    type: "Journal",
    url_home:
      "https://www.sciencedirect.com/journal/journal-of-economic-psychology",
    url_rss: "https://rss.sciencedirect.com/publication/science/01674870",
    update_frequency: "Every few months",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: "Not on twitter",
  },
  {
    title: "The Behavioural Scientist",
    type: "BeSci Media",
    url_home: "https://behavioralscientist.org/",
    url_rss: "https://behavioralscientist.org/feed/",
    update_frequency: "Monthly",
    last_checked: "2023-07-12",
    geo_region: "Global",
    open_access: true,
    notes: null,
  },
  {
    title: "The 20% statistician (methods)",
    type: "BeSci Media",
    url_home: "http://daniellakens.blogspot.com/",
    url_rss: "http://daniellakens.blogspot.com/feeds/posts/default",
    update_frequency: "Every few months",
    last_checked: "2023-07-14",
    geo_region: "Netherlands",
    open_access: false,
    notes: null,
  },
  {
    title: "BE Hub",
    type: "Consultancy/ThinkTank",
    url_home: "https://www.behavioraleconomics.com/blog/",
    url_rss: "https://www.behavioraleconomics.com/feed/",
    update_frequency: "Monthly",
    last_checked: "2023-07-14",
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "J-PAL",
    type: "Institution/Academic Department",
    url_home: "https://www.povertyactionlab.org/",
    url_rss: "https://www.povertyactionlab.org/news.xml",
    update_frequency: "Daily",
    last_checked: "2023-07-12",
    geo_region: "Global",
    open_access: true,
    notes: null,
  },
  {
    title: "World Bank Blogs",
    type: "Institution/Academic Department",
    url_home: "https://blogs.worldbank.org/",
    url_rss: "https://blogs.worldbank.org/feed/impactevaluations/rss.xml",
    update_frequency: "Daily",
    last_checked: "2023-07-12",
    geo_region: "Global",
    open_access: true,
    notes: "No email alert option",
  },
  {
    title: "Behavioural Science & Policy Association",
    type: "Institution/Academic Department",
    url_home: "https://behavioralpolicy.org/",
    url_rss: "https://behavioralpolicy.org/feed/",
    update_frequency: null,
    last_checked: "2023-07-14",
    geo_region: null,
    open_access: true,
    notes: null,
  },
  {
    title: "Jason Collins (Academic & Consultant)",
    type: "Blog / Substack / Newsletter",
    url_home: "https://www.jasoncollins.blog/about",
    url_rss: "https://www.jasoncollins.blog/index.xml",
    update_frequency: "Every few months",
    last_checked: null,
    geo_region: null,
    open_access: true,
    notes: null,
  },
]

const TOPICS: Array<TopicNew> = [
  { umbrella: "HASED", title: "Education", core: true, notes: "" },
  { umbrella: "HASED", title: "Early Years", core: true, notes: "" },
  {
    umbrella: "HASED",
    title: "Home Affairs & Security",
    core: true,
    notes: "",
  },
  {
    umbrella: "HASED",
    title: "Social Capital and Cohesion",
    core: true,
    notes: "Overlaps with IP Peacebuilding & Social Cohesion",
  },
  { umbrella: "HASED", title: "Social mobility", core: false, notes: "" },
  {
    umbrella: "HASED",
    title: "Digital/tech interventions",
    core: false,
    notes: "",
  },
  { umbrella: "IP", title: "International Programmes", core: true, notes: "" },
  {
    umbrella: "IP",
    title: "International Programmes Capacity Building",
    core: true,
    notes: "Reflects nature of the work rather than policy area",
  },
  { umbrella: "IP", title: "Conflict", core: true, notes: "" },
  {
    umbrella: "IP",
    title: "Violence against Women and Girls",
    core: true,
    notes: "",
  },
  {
    umbrella: "IP",
    title: "Peacebuilding & social cohesion",
    core: false,
    notes: "Overlaps with HASED Social Capital & Social Cohesion",
  },
  {
    umbrella: "IP",
    title: "EMEA expansion",
    core: false,
    notes: "Not sure this reflects external work or internal strategy",
  },
  {
    umbrella: "Economy",
    title: "Energy & Sustainability",
    core: true,
    notes: "",
  },
  {
    umbrella: "Economy",
    title: "Consumer & Business Markets",
    core: true,
    notes: "",
  },
  {
    umbrella: "Economy",
    title: "Labour Markets & Household finances",
    core: true,
    notes: "",
  },
  {
    umbrella: "Economy",
    title: "Equality, Diversity & Inclusion",
    core: true,
    notes: "",
  },
  {
    umbrella: "Economy",
    title: "Leveling Up & Regional Growth",
    core: false,
    notes: "",
  },
  { umbrella: "Health & Wellbeing", title: "Health", core: true, notes: "" },
  {
    umbrella: "Health & Wellbeing",
    title: "Mental Health & Wellbeing",
    core: true,
    notes: "",
  },
  {
    umbrella: "Health & Wellbeing",
    title: "Social Care",
    core: true,
    notes: "",
  },
  {
    umbrella: "Health & Wellbeing",
    title: "Homelessness",
    core: false,
    notes: "",
  },
  {
    umbrella: "Health & Wellbeing",
    title: "Loneliness",
    core: false,
    notes: "",
  },
  {
    umbrella: "Health & Wellbeing",
    title: "Obesity",
    core: false,
    notes: "",
  },
  { umbrella: "Cross-cutting", title: "AI and BI", core: true, notes: "" },
  {
    umbrella: "Cross-cutting",
    title: "Methods innovation",
    core: true,
    notes: "",
  },
  {
    umbrella: "Cross-cutting",
    title: "Relevant to all areas",
    core: true,
    notes: "",
  },
  {
    umbrella: "Other",
    core: false,
    title: "Skip",
    notes:
      "Use this for complex samples which you don't want to label one way or another",
  },
  {
    umbrella: "Other",
    core: false,
    title: "Not relevant",
    notes:
      "Use this for samples which aren't relevant to your topics of interest",
  },
]

async function seed() {
  console.log("Inserting data...")
  await insertSources(SOURCES)
  await insertTopics(TOPICS)
  await db.destroy()
  console.log("Done!")
}

seed()
